[package]
name        = "asciisavers"
version     = "0.1.0"
author      = "Coderspark"
description = "A small collection of ascii screensavers"
edition     = "2021"
license     = "GPL-3.0"

[dependencies]
crossterm = "0.28.1"
rand = "0.8.5"
